name: API Test Restassured Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: API Test Job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Execute Gradle build
      run: gradle build

    - name: Run Tests
      run: ./gradlew test

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-results
        path: build/reports/tests/test
        
    - name: Summary
      uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: JEST Tests
        path: 'build/reports/tests/test/*.xml'
        reporter: jest-junit
    
    # - name: Generate Test Summary
    #   uses: janisz/action@v2
    #   if: always()
    #   with:
    #     paths: "build/reports/tests/test"
