name: API Test Restassured Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: API Test Job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Execute Gradle build
      run: gradle build

    - name: Run Test
      run: ./gradlew test

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-results
        path: build/reports/tests/test

    - name: Display Test Summary
      id: test-summary
      run: |
        total_tests=$(grep 'tests, ' build/reports/tests/test/index.html | sed 's/ tests,.*//')
        passed_tests=$(grep 'Tests' build/reports/tests/test/index.html | sed 's/.*>\(.*\) Tests Passed<.*/\1/')
        failed_tests=$((total_tests - passed_tests))
        echo "Test Summary: $passed_tests passed, $failed_tests failed"

    - name: Set Test Summary
      id: set-test-summary
      run: |
        echo "Test Summary: ${{ steps.test-summary.outputs.test-summary }}" >> $GITHUB_ENV
